# Generated by Django 5.0.3 on 2024-03-29 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Videos", "0002_alter_video_video"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
