# Generated by Django 5.0.3 on 2024-03-29 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Videos", "0003_alter_video_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="video",
            name="comments_count",
        ),
    ]
