# Generated by Django 5.0.3 on 2024-03-19 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('birthday', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('P', 'Preferred not to say')], default='P', max_length=20)),
                ('phone_number', models.IntegerField()),
                ('followers_count', models.IntegerField(default=0)),
                ('followings_count', models.IntegerField(default=0)),
            ],
        ),
    ]
