version: '3'

services:
  app:
    build:
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: >
      sh -c "python -m pip install Pillow &&
             python3 manage.py migrate &&
             python3 manage.py runserver 0.0.0.0:8000"

    environment:
      - DOCKERIZED=True
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/video_hosting
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}

    depends_on:
      - db
      - rabbitmq
      - celery-worker
    restart: always
    env_file:
      - .env
  db:
    image: postgres
    environment:
      - POSTGRES_DB=video_hosting
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/
    restart: always

  my-pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=video.hosting.ua@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=pass123
    ports:
      - "80:80"
    restart: always

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "celeryuser"
      RABBITMQ_DEFAULT_PASS: "celeryuser"
    restart: always

  celery-worker:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
    environment:
      - BROKER_URL=pyamqp://celeryuser:celeryuser@rabbitmq:5672//
      - CELERY_RESULT_BACKEND=rpc://
    command: celery -A videoHosting worker
    restart: always
    env_file:
      - .env

volumes:
  pgdata:

